#!/usr/bin/env python
import gtk
import appindicator
import os
import commands
import gtk
import sys

class GriveIndicator:
    def __init__(self):
	self.ind = appindicator.Indicator("Grive Indicator",
                                           "indicator-messages",
                                           appindicator.CATEGORY_APPLICATION_STATUS)
	self.ind.set_status(appindicator.STATUS_ACTIVE)
	self.ind.set_attention_icon("indicator-messages-new")
	self.ind.set_icon_theme_path("/usr/local/indicator-grive/")
	self.ind.set_icon('drive')
        self.menu_setup()
        self.ind.set_menu(self.menu)
    def menu_setup(self):
        self.menu = gtk.Menu()

	self.infoGrive_item = gtk.MenuItem(self.infoGrive())
	self.infoGrive_item.set_sensitive(False)
	self.infoGrive_item.show()

	self.Restart_item = gtk.MenuItem("Sync Now / Restart")
        self.Restart_item.connect("activate", self.doRestart)
        self.Restart_item.show()

	self.seperator1_item = gtk.SeparatorMenuItem()
	self.seperator1_item.show()

	self.Remote_item = gtk.MenuItem("Open remote GDrive")
        self.Remote_item.connect("activate", self.openRemote)
        self.Remote_item.show()

	self.Local_item = gtk.MenuItem("Open local GDrive")
        self.Local_item.connect("activate", self.openLocal)
        self.Local_item.show()

	self.seperator2_item = gtk.SeparatorMenuItem()
	self.seperator2_item.show()

	self.setInterval_item = gtk.MenuItem("Change sync interval")
        self.setInterval_item.connect("activate", self.setInterval)
        self.setInterval_item.show()

	self.seperator3_item = gtk.SeparatorMenuItem()
	self.seperator3_item.show()

	self.DarkTheme_item = gtk.MenuItem("Use dark theme icon")
        self.DarkTheme_item.connect("activate", self.setDarkTheme)
        self.DarkTheme_item.show()

	self.LightTheme_item = gtk.MenuItem("Use light theme icon")
        self.LightTheme_item.connect("activate", self.setLightTheme)
        self.LightTheme_item.show()

	self.seperator4_item = gtk.SeparatorMenuItem()
	self.seperator4_item.show()

	self.Quit_item = gtk.MenuItem("Quit")
        self.Quit_item.connect("activate", self.Quit)
        self.Quit_item.show()

	self.menu.append(self.infoGrive_item)
	self.menu.append(self.Restart_item)
	self.menu.append(self.seperator1_item)
	self.menu.append(self.Remote_item)
	self.menu.append(self.Local_item)
	self.menu.append(self.seperator2_item)
	self.menu.append(self.setInterval_item)
	self.menu.append(self.seperator3_item)
	self.menu.append(self.DarkTheme_item)
	self.menu.append(self.LightTheme_item)
	self.menu.append(self.seperator4_item)
	self.menu.append(self.Quit_item)

    def infoGrive(self):
	os.system("/usr/local/indicator-grive/grive-restart")
	stat, out = commands.getstatusoutput("/usr/local/indicator-grive/status")
	out = out.replace("grive", "Grive")
	return out

    def doRestart(self, dude):
	os.system("/usr/local/indicator-grive/restart")

    def openRemote(self, dude):
	os.system("xdg-open 'https://drive.google.com/'")

    def openLocal(self, dude):
	os.system("xdg-open 'Google Drive'")

    def setInterval(self, dude):
	os.system("sudo /usr/local/indicator-grive/set-interval && /usr/local/indicator-grive/restart")

    def setDarkTheme(self, dude):
	os.system("sudo /usr/local/indicator-grive/icon4darktheme && /usr/local/indicator-grive/restart")

    def setLightTheme(self, dude):
	os.system("sudo /usr/local/indicator-grive/icon4lighttheme && /usr/local/indicator-grive/restart")

    def Quit(self, dude):
	os.system("/usr/local/indicator-grive/quit")

    def ignore(*args):
	return gtk.TRUE

    def main(self):
        gtk.main()

if __name__ == "__main__":
    indicator = GriveIndicator()
    indicator.main()
