#!/bin/bash
cp -f /usr/local/grive-indicator/drive-dark.png /usr/local/grive-indicator/drive.png
killall python /usr/local/bin/grive-indicator
killall grive
killall grive-sync
/usr/local/bin/grive-indicator
