#!/bin/bash
#!/bin/bash
# Get sudo password
sudo_password="$( gksudo --print-pass --message 'Provide permission to make system changes: Type your password or press Cancel.' -- : 2>/dev/null )"
# Check for null entry or cancellation.
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
    exit 4
fi
# Check that the password is valid.
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
    exit 4
fi
# Execute sudo action
sudo -Sp '' cp -f /usr/local/grive-indicator/drive-light.png /usr/local/grive-indicator/drive.png <<<"${sudo_password}"
# Restart
killall python /usr/local/bin/grive-indicator
killall grive-sync
/usr/local/bin/grive-indicator

