#!/bin/bash

REPO=$(which drive | grep -c "bin/drive")

if [ "$REPO" = "0" ]
then
	sudo add-apt-repository ppa:twodopeshaggy/drive -y
	sudo apt-get update
	sudo apt-get install drive
fi

if ! [[ -d "$HOME/Drive" ]]
then
    mkdir -p "$HOME/Drive"
fi

if ! [[ -d "$HOME/Drive/.gd" ]]
then
    drive init "$HOME/Drive"
fi
