#!/bin/bash

pkill -f "/bin/bash /usr/local/indicator-drive/indicator-drive.sh drive-sync"
pkill -f "/bin/bash /usr/local/indicator-drive/indicator-drive.sh drive-restart"
pkill -f "python /usr/local/indicator-drive/indicator-drive.py"

DEPENDENCY1=$(apt-cache search python-appindicator | grep "python-appindicator - " | awk -F " - " '{print $1}')
if [ "$DEPENDENCY1" = "python-appindicator" ]
then
	sudo apt-get install python-appindicator
fi
DEPENDENCY2=$(which zenity | grep -c "bin/zenity")
if [ "$DEPENDENCY2" = "0" ]
then
	sudo apt-get install zenity
fi

sudo rm -Rf "/usr/local/indicator-drive"
sudo mkdir -p "/usr/local/indicator-drive"
	
sudo cp -f indicator-drive.py /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/indicator-drive.py
sudo chmod 755 /usr/local/indicator-grive/indicator-drive.py

sudo cp -f indicator-drive.sh /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/indicator-drive.sh
sudo chmod 755 /usr/local/indicator-grive/indicator-drive.sh

sudo cp -f drive.svg /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive.svg
sudo chmod a+rw /usr/local/indicator-grive/drive.svg
sudo cp -f drive-color.svg /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive-color.svg
sudo chmod a+r /usr/local/indicator-grive/drive-color.svg
sudo cp -f drive-dark.svg /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive-dark.svg
sudo chmod a+r /usr/local/indicator-grive/drive-dark.svg
sudo cp -f drive-light.svg /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive-light.svg
sudo chmod a+r /usr/local/indicator-grive/drive-light.svg

sudo cp -f indicator-drive.desktop /etc/xdg/autostart/
sudo cp -f indicator_drive.desktop /usr/share/applications/

echo "Installation completed. Now indicator-drive is ready to start at every login. But make sure that drive is setup and configured before that."
