#!/bin/bash

pkill -f "python /usr/local/bin/grive-indicator"
killall grive
killall grive-sync

REPO=$(apt-cache search grive | grep "grive - " | awk -F " - " '{print $1}')
if [ "$REPO" = "grive" ]; then
	sudo apt-get install grive python-appindicator zenity
else
	sudo add-apt-repository ppa:nilarimogard/webupd8 -y
	sudo apt-get update
	sudo apt-get install grive python-appindicator zenity
fi

sudo rm -Rf "/usr/local/grive-indicator"
sudo rm -Rf "/usr/local/indicator-grive"
sudo mkdir -p "/usr/local/indicator-grive"
	
sudo cp -f grive-indicator /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/grive-indicator
sudo chmod 755 /usr/local/indicator-grive/grive-indicator
sudo ln -sf /usr/local/indicator-grive/grive-indicator /usr/local/bin/grive-indicator

sudo cp -f grive-restart /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/grive-restart
sudo chmod 755 /usr/local/indicator-grive/grive-restart

sudo cp -f grive-sync /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/grive-sync
sudo chmod a+x /usr/local/indicator-grive/grive-sync

sudo cp -f icon4darktheme /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/icon4darktheme
sudo chmod a+x /usr/local/indicator-grive/icon4darktheme

sudo cp -f icon4lighttheme /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/icon4lighttheme
sudo chmod a+x /usr/local/indicator-grive/icon4lighttheme

sudo cp -f quit /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/quit
sudo chmod a+x /usr/local/indicator-grive/quit

sudo cp -f restart /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/restart
sudo chmod a+x /usr/local/indicator-grive/restart

sudo cp -f set-interval /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/set-interval
sudo chmod a+x /usr/local/indicator-grive/set-interval

sudo cp -f show-interval /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/show-interval
sudo chmod a+x /usr/local/indicator-grive/show-interval

sudo cp -f drive.png /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive.png
sudo cp -f drive-dark.png /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive-dark.png
sudo cp -f drive-light.png /usr/local/indicator-grive/
sudo chown root:root /usr/local/indicator-grive/drive-light.png
sudo chmod a+r /usr/local/indicator-grive/*.png

sudo cp -f grive-indicator-sudoers /etc/sudoers.d/
sudo chmod 644 /etc/sudoers.d/grive-indicator-sudoers

sudo cp -f grive-indicator.desktop /etc/xdg/autostart/
sudo cp -f grive-indicator.desktop /usr/share/applications/

echo "Installation completed. Now grive-indicator is ready to start at every login. But make sure that grive is setup and configured before that."
